In [1]:
import tensorflow as tf
import pathlib
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import tensorflow.data


np.set_printoptions(precision=4)

In [2]:
# tf.tensor, TF中基本都是张量在进行流转
# Compute some values using a Tensor
c = tf.constant([[1.0, 2.0], 
                 [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], 
                 [0.0, 1.0]])
e = tf.matmul(c, d)
print(e)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


## #tf.data.dataset.from_tensor_slices


In [19]:
# 二位数组，拆除第一维
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4]])
print(list(dataset.as_numpy_iterator()))
# 对于元组来说，拆除的是元组内部的每一项的维度，最后再次合成元组
dataset = tf.data.Dataset.from_tensor_slices(([1, 2], [3, 4], [5, 6]))
print(list(dataset.as_numpy_iterator()))
# 拆除第一维，就是拆外面的数组
dataset = tf.data.Dataset.from_tensor_slices([(1, 2), (3, 4), (5, 6)])
print(list(dataset.as_numpy_iterator()))
# 参数是dict，拆除dict的value的维度
dataset = tf.data.Dataset.from_tensor_slices({"a": [1, 2], "b": [3, 4]})
print(list(dataset.as_numpy_iterator()))
# dataset = tf.data.Dataset.from_tensor_slices({"a": (1, 2), "b": (3, 4)}) 这个会报错，说明拆不了元组
# 参数是元组，拆里面每一项，每一项是dict，拆dict的value， ({a:1, b:3},{c:5}) , ({a:2, b:4},{c:6})
dataset = tf.data.Dataset.from_tensor_slices(({"a": [1, 2], "b": [3, 4]}, {"c": [5, 6]}))
print(list(dataset.as_numpy_iterator()))
# 太离谱了，这特么也可以 ({'a': {'aa': 1}, 'b': {'bb': 3}}, {'c': {'cc': 5}}), ({'a': {'aa': 2}, 'b': {'bb': 4}}, {'c': {'cc': 6}})
dataset = tf.data.Dataset.from_tensor_slices(({"a": {"aa": [1, 2]}, "b": {"bb" : [3, 4]}}, {"c": {"cc": [5, 6]}}))
print(list(dataset.as_numpy_iterator()))

# Two tensors can be combined into one Dataset object.
features = tf.constant([[1, 3], [2, 1], [3, 3]]) # ==> 3x2 tensor
labels = tf.constant(['A', 'B', 'A']) # ==> 3x1 tensor
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
# Both the features and the labels tensors can be converted
# to a Dataset object separately and combined after.
features_dataset = tf.data.Dataset.from_tensor_slices(features)
labels_dataset = tf.data.Dataset.from_tensor_slices(labels)
dataset = tf.data.Dataset.zip((features_dataset, labels_dataset))
# A batched feature and label set can be converted to a Dataset
# in similar fashion.
batched_features = tf.constant([[[1, 3], [2, 3]],
                                [[2, 1], [1, 2]],
                                [[3, 3], [3, 2]]], shape=(3, 2, 2))
batched_labels = tf.constant([['A', 'A'],
                              ['B', 'B'],
                              ['A', 'B']], shape=(3, 2, 1))
dataset = tf.data.Dataset.from_tensor_slices((batched_features, batched_labels))
for element in dataset.as_numpy_iterator():
  print(element)


[array([1, 2]), array([3, 4])]
[(1, 3, 5), (2, 4, 6)]
[array([1, 2]), array([3, 4]), array([5, 6])]
[{'a': 1, 'b': 3}, {'a': 2, 'b': 4}]
[({'a': 1, 'b': 3}, {'c': 5}), ({'a': 2, 'b': 4}, {'c': 6})]
[({'a': {'aa': 1}, 'b': {'bb': 3}}, {'c': {'cc': 5}}), ({'a': {'aa': 2}, 'b': {'bb': 4}}, {'c': {'cc': 6}})]
(array([[1, 3],
       [2, 3]]), array([[b'A'],
       [b'A']], dtype=object))
(array([[2, 1],
       [1, 2]]), array([[b'B'],
       [b'B']], dtype=object))
(array([[3, 3],
       [3, 2]]), array([[b'A'],
       [b'B']], dtype=object))
