In [59]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(){return true}  // 设置不出现滑动窗口 true, auto, false

<IPython.core.display.Javascript object>

In [60]:
### https://github.com/garfieldsun/recsys/blob/master/FM/FM_numpy.ipynb
import numpy as np
from random import normalvariate

In [61]:
data = np.array([[6,148,72,35,0,33.6,0.627,50],
                 [1,85,66,29,0,26.6,0.351,31],
                 [8,183,64,0,0,23.3,0.672,32],
                 [1,89,66,23,94,28.1,0.167,21],
                 [0,137,40,35,168,43.1,2.288,33]])
label=np.array([1,0,1,0,1])
print(data.shape)

(5, 8)


In [62]:
def sigmoid(inx):
    return 1.0 / (1 + np.exp(-inx))

In [63]:
def fit(data, alpha=0.01, k=3, iter_num=20):
    """alpha为学习率，k为v的隐特征数，iter_num为迭代次数初始化所需要的参数"""
    m,n = data.shape    #m为样本个数，n为特征个数 5 * 8
    w = np.zeros(n)
    print(w)
    w_0 = 0.
    # 随机数×构造的特征向量
    v = normalvariate(0, 0.2) * np.ones((n, k)) # 8 * 3, 每个特征对应的向量，交叉特征就是，不同行数相乘
    # 每轮每个样本
    for it in range(iter_num):
        for x in range(m):
            '''前向传播得到预测值'''
            inter_1 = data[x].dot(v)
            inter_2 = np.multiply(data[x],data[x]).dot((np.multiply(v,v)))
            interaction =np.sum(inter_1*inter_1-inter_2)/2
            p = w_0+ w.dot(data[x])+interaction
            print('预测值：',p)

            '''损失函数'''
            loss = sigmoid(label[x]*p)-1

            '''随机梯度下降，得到各个权重'''
            w_0 = w_0 - alpha*loss*label[0]   
            for i in range(n):
                if data[x, i] != 0:
                    w[i] = w[i] - alpha*loss*label[0]*data[0][i]     
                    for j in range(k):
                        v[i,j]=v[i,j]-alpha*loss*label[0]*(data[0][i]*(inter_1[j])-v[i,j]*data[0][i]*data[0][i])
    return w_0,w,v
w_0,w,v=fit(data)

[0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]]


In [64]:
print('w_0:{}\n w:{}\n v:{}'.format(w_0,w,v))

w_0:0.0
 w:[0. 0. 0. 0. 0. 0. 0. 0.]
 v:[[-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]
 [-0.19393362 -0.19393362 -0.19393362]]
