# sun: tf.sequence_mask

In [4]:
import tensorflow as tf
from tensorflow import keras

https://blog.csdn.net/xinjieyuan/article/details/95760679 : 对sequence_mask进行讲解

In [5]:
# 例子举得是，第一个参数length是代表nlp中每个句子的长度，然后生成的是，对每个句子的掩码
# 第一个参数为列表：列表中每一个数字代表序列的长度
# 第一个参数为数字，代表一个序列的长度
print(tf.sequence_mask([3, 4], 5)) # 一个列表，有2个序列 mask：2 * 5 (2个序列，每个序列5个掩码)
print(tf.sequence_mask([2], 5))  #  一个列表，有1个序列 mask：1 * 5
print(tf.sequence_mask([1], 5))
print(tf.sequence_mask(1, 5)) # 就一个序列，mask ： 5

tf.Tensor(
[[ True  True  True False False]
 [ True  True  True  True False]], shape=(2, 5), dtype=bool)
tf.Tensor([[ True  True False False False]], shape=(1, 5), dtype=bool)
tf.Tensor([[ True False False False False]], shape=(1, 5), dtype=bool)
tf.Tensor([ True False False False False], shape=(5,), dtype=bool)


#### sequence_mask对tensor操作的理解
input本身是一个特征数为1的输入层，样本就是 [x], 多个样本就类似于 [1], [2], [4] ...., 掩码后类似于，[[...(20位)]] 多个样本的掩码 [[...(20位)]], [[...(20位)]], ..... 所以input的形状是：none * 1，最后掩码的形状是 none * 1 * 20 ，每个样本，一个特征，这个特征20维度的掩码

input 如果我们创建keras(2,)这代表这个输入层有两个特征，样本就是 [x, y], 多个样本就类似于 [1, 2], [3, 4], [5, 6]...., 掩码后类似于 [[...(20位)], [...(20位)]]
所以input的形状：none * 2, 最后掩码的形状是：none * 2 * 20, 每个样本，2个特征，每个特征都有20维度的掩码

In [6]:
# 这是一个张量，维度是1, 代表了一个序列的长度
input = keras.Input(shape=(1,), name='input', dtype=tf.int64)
print(input)
# 掩码长度维20的时候，生成的掩码张量形状为：[1, 20]
input_sequence = tf.sequence_mask(input, maxlen=20, dtype=tf.float32)
print(input_sequence)

# 这是一个形状为[2, 4]的张量
input = keras.Input(shape=(2,), name='input', dtype=tf.int64)
input_sequence = tf.sequence_mask(input, maxlen=20, dtype=tf.float32)
print(input_sequence)

KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.int64, name='input'), name='input', description="created by layer 'input'")
KerasTensor(type_spec=TensorSpec(shape=(None, 1, 20), dtype=tf.float32, name=None), name='tf.sequence_mask_2/SequenceMask/Cast_1:0', description="created by layer 'tf.sequence_mask_2'")
KerasTensor(type_spec=TensorSpec(shape=(None, 2, 20), dtype=tf.float32, name=None), name='tf.sequence_mask_3/SequenceMask/Cast_1:0', description="created by layer 'tf.sequence_mask_3'")
