# sun: tf.sequence_mask

In [4]:
import tensorflow as tf
from tensorflow import keras

https://blog.csdn.net/xinjieyuan/article/details/95760679 : 对sequence_mask进行讲解

In [10]:
# 例子举得是，第一个参数length是代表nlp中每个句子的长度，然后生成的是，对每个句子的掩码
print(tf.sequence_mask([3, 4], 5)) # 数据形状：1 * 2   mask：1 * 2 * 5
print(tf.sequence_mask([2], 5))  # 数据形状：1 * 1 mask：1*1*5
print(tf.sequence_mask([1], 5))
print(tf.sequence_mask(1, 5))

tf.Tensor(
[[ True  True  True False False]
 [ True  True  True  True False]], shape=(2, 5), dtype=bool)
tf.Tensor([[ True  True False False False]], shape=(1, 5), dtype=bool)
tf.Tensor([[ True False False False False]], shape=(1, 5), dtype=bool)
tf.Tensor([ True False False False False], shape=(5,), dtype=bool)


In [8]:
# 这是一个张量，维度是1, 不管怎样，这还是个向量，而不是一个标量
input = keras.Input(shape=(1,), name='input', dtype=tf.int64)
# 掩码长度维20的时候，生成的掩码张量形状为：[1, 20]
input_sequence = tf.sequence_mask(input, maxlen=20, dtype=tf.float32)
print(input_sequence)

# 这是一个形状为[2, 4]的张量
input = keras.Input(shape=(2, 4), name='input', dtype=tf.int64)
input_sequence = tf.sequence_mask(input, maxlen=20, dtype=tf.float32)
print(input_sequence)

KerasTensor(type_spec=TensorSpec(shape=(None, 1, 20), dtype=tf.float32, name=None), name='tf.sequence_mask_3/SequenceMask/Cast_1:0', description="created by layer 'tf.sequence_mask_3'")
KerasTensor(type_spec=TensorSpec(shape=(None, 2, 4, 20), dtype=tf.float32, name=None), name='tf.sequence_mask_4/SequenceMask/Cast_1:0', description="created by layer 'tf.sequence_mask_4'")
