In [1]:
import keras
import tensorflow as tf
from tensorflow import keras

Using TensorFlow backend.


## 对tensor的理解

keras.Input(shape=(1,), name='input', dtype=tf.int64) 这行代码表示创建了一个名为 input 的输入层，这个输入层有一个特征，维度为 1 维，数据类型为整数（int64）。
尽管维度是1维，但是在 TensorFlow 中，即使是一维的特征也需要被表示为张量，因此在这里使用了 (1,) 表示维度为1
shape=(1,) 中的 1 表示这个特征的维度为1，而不是表示这个特征本身是一个向量。在这种情况下，每个样本只包含一个特征值。
所以可以想象一个dataframe
      特征1
样本1   1
样本2   2
样本3   3
...

keras.Input(shape=(1,))代表的就是这样的输入层

#### 所以在定义输入层时，是不知道样本数相关概念的对吧？
在定义神经网络模型的输入层时，通常是不需要明确指定样本数量的。输入层的形状（shape）通常用来指定每个样本的特征数量，而样本的数量通常在训练时由输入数据的批次大小（batch size）确定。
在训练神经网络时，您会将整个数据集分成批次（batches）来输入模型进行训练。每个批次中包含一定数量的样本，这个数量就是批次大小。因此，样本数量是由数据集中的样本总数和批次大小共同决定的。
在定义神经网络模型时，您只需要关注每个样本的特征数量，而不需要显式地指定样本数量。样本数量在训练时会根据批次大小动态确定。

In [2]:
# shape(x,) 中x代表特征数，这个input代表有一个特征，每个样本只包含一个特征值
input = keras.Input(shape=(1,), name='input', dtype=tf.int64)

#### keras.Input(shape=(2,))的理解
keras.Input(shape=(2,), name='input', dtype=tf.int64) 这行代码表示创建了一个名为 input 的输入层，这个输入层有两个特征，每个特征的维度为 1 维，数据类型为整数（int64）。
在这种情况下，每个样本有两个特征，每个特征都是一个单独的维度为1的向量。这种表示方式适用于许多机器学习模型，包括神经网络模型，其中每个样本可以包含多个特征。
因此，shape=(2,) 中的 2 表示这个输入层有两个特征，每个特征的维度为1。这种方式适用于表示多特征的情况，每个特征都是一个单独的维度。
所以可以想象一个dataframe
      特征1  特征2
样本1   1      2
样本2   2      7
样本3   3      8
...

#### feature_column转化特征
在使用 keras.Input 定义输入层时，shape 参数中的第一个值表示特征的数量，而每个特征本身是一个一维向量。
如果您使用 feature_column 将一个数字特征分桶成了6个桶，那么可以将这个数字特征转化为6个特征来输入模型。每个特征代表一个桶，每个特征是一个一维向量。
例如，如果您有一个数字特征被分成了6个桶，您可以将这6个桶作为6个独立的特征输入到模型中，每个特征是一个一维向量，表示该特征的值。这种方式可以帮助模型更好地理解和利用原始数据的特征

In [3]:
# a特征每个样本是一个数字
data = {'a': [15, 9, 17, 19, 21, 18, 25, 30]}
a = tf.feature_column.numeric_column('a')
a_buckets = tf.feature_column.bucketized_column(a,
   boundaries=[10, 15, 20, 25, 30])
feature_layer1 = tf.keras.layers.DenseFeatures([a_buckets])
## 这里一个特征转化为6个特征
print(feature_layer1(data))    ## shape : 8 * 6

tf.Tensor(
[[0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]], shape=(8, 6), dtype=float32)
